# Generated by Django 4.1.5 on 2023-02-09 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drone', models.CharField(max_length=60)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Identification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.TextField()),
                ('species', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.URLField()),
                ('type', models.CharField(max_length=20)),
                ('geo_data', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('type', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ObservationMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aviary.media')),
                ('observation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aviary.observation')),
            ],
        ),
        migrations.CreateModel(
            name='IdentificationObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aviary.identification')),
                ('observation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aviary.observation')),
            ],
        ),
        migrations.CreateModel(
            name='FlightMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aviary.flight')),
                ('media_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aviary.media')),
            ],
        ),
        migrations.AddField(
            model_name='flight',
            name='pilot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aviary.users'),
        ),
    ]
