# Generated by Django 4.1.5 on 2023-02-21 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviary', '0002_alter_flight_pilot_delete_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.CharField(max_length=200),
        ),
    ]
