# Generated by Django 4.1.5 on 2023-02-21 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aviary', '0003_alter_media_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='geo_data',
            new_name='geometry',
        ),
    ]
