# Generated by Django 4.1.5 on 2023-02-21 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aviary', '0004_rename_geo_data_media_geometry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flightmedia',
            old_name='flight_id',
            new_name='flight',
        ),
        migrations.RenameField(
            model_name='flightmedia',
            old_name='media_id',
            new_name='media',
        ),
        migrations.RenameField(
            model_name='identificationobservation',
            old_name='identification_id',
            new_name='identification',
        ),
        migrations.RenameField(
            model_name='identificationobservation',
            old_name='observation_id',
            new_name='observation',
        ),
        migrations.RenameField(
            model_name='observationmedia',
            old_name='media_id',
            new_name='media',
        ),
        migrations.RenameField(
            model_name='observationmedia',
            old_name='observation_id',
            new_name='observation',
        ),
    ]
