# Generated by Django 4.1.5 on 2023-02-21 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aviary', '0005_rename_flight_id_flightmedia_flight_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flight',
            options={'default_related_name': 'flights'},
        ),
        migrations.AlterModelOptions(
            name='flightmedia',
            options={'default_related_name': 'flight_medias'},
        ),
        migrations.AlterModelOptions(
            name='identification',
            options={'default_related_name': 'identifications'},
        ),
        migrations.AlterModelOptions(
            name='identificationobservation',
            options={'default_related_name': 'identification_observations'},
        ),
        migrations.AlterModelOptions(
            name='media',
            options={'default_related_name': 'medias'},
        ),
        migrations.AlterModelOptions(
            name='observation',
            options={'default_related_name': 'observations'},
        ),
        migrations.AlterModelOptions(
            name='observationmedia',
            options={'default_related_name': 'observation_medias'},
        ),
    ]
