# Generated by Django 4.1.5 on 2023-04-25 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aviary', '0006_alter_flight_options_alter_flightmedia_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('anafi_id', models.CharField(max_length=60)),
            ],
        ),
        migrations.AlterField(
            model_name='flight',
            name='drone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aviary.drone'),
        ),
    ]
