# Generated by Django 4.1.5 on 2023-04-25 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviary', '0007_drone_alter_flight_drone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drone',
            old_name='anafi_id',
            new_name='drone_id',
        ),
        migrations.AddField(
            model_name='drone',
            name='make',
            field=models.CharField(default='Parrot', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drone',
            name='model',
            field=models.CharField(default='Anafi', max_length=60),
            preserve_default=False,
        ),
    ]
