# Generated by Django 4.1.5 on 2023-04-25 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviary', '0008_rename_anafi_id_drone_drone_id_drone_make_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drone',
            name='drone_id',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='drone',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
