# Generated by Django 4.1.5 on 2023-04-25 15:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviary', '0009_alter_drone_drone_id_alter_drone_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='run_id',
            field=models.CharField(default=datetime.datetime(2023, 4, 25, 15, 56, 8, 68534, tzinfo=datetime.timezone.utc), max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='media',
            name='recorded',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 25, 15, 56, 13, 380851, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
